package excepciones;

import java.util.Date;
import java.util.Scanner;

public class FechaException extends Exception {

	public static Scanner teclado = new Scanner(System.in);

	public static Date validarFecha() {

		int dia = 0, mes = 0, anio = 0;

		try {
			while (anio == 0) {
				System.out.println("Ingrese el año");
				anio = validarInt(teclado);
				if (anio < 1900 || anio > 2022) {
					System.err.println("El año debe estar entre 1900 y 2022");
					anio = 0;
				}
			}

			while (mes == 0) {
				System.out.println("Ingrese el mes");
				mes = validarInt(teclado);
				if (mes < 1 || mes > 12) {
					System.err.println("El mes debe estar comprendido entre 1 y 12");
					mes = 0;
				} 
			}
			
			while(dia == 0) {
				System.out.println("Ingrese el dia");
				dia = validarInt(teclado);
				if(dia < 1 || dia>31) {
					System.err.println("El día debe ser válido entre 1 y 31 (según el mes)");
				}else if (mes == 4 || mes == 6 || mes == 9 || mes == 11 ) {
					if(dia > 30) {
						System.err.println("El día para el mes ingresado ");
					}
				}
			}

		} catch (Exception e) {
			System.err.println("Algo sucedió mal - " + e);
		}

		return new Date(anio - 1900, mes - 1, dia);
	}

	public static int validarInt(Scanner arg) {

		int valor;

		if (arg.hasNextInt()) {
			valor = arg.nextInt();
		} else {
			System.err.println("Número no válido");
			valor = 0;
		}
		arg.nextLine();

		return valor;
	}

}
